# -*- coding: utf-8 -*-
"""add.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdTpgBxneyMo4aXVZhqlvvqltnuYOXDJ
"""

pip install streamlit

import streamlit as st
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib
import os

# Load or train model only once
@st.cache_resource
def load_model_and_data():
    # Load CSV
    ques = pd.read_csv('kamaraj_college_faq.csv')
    ques.dropna(inplace=True)

    # Encode answers
    le = LabelEncoder()
    ques['Answer_Label'] = le.fit_transform(ques['Answer'])

    # Vectorize questions
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(ques['Question'])
    y = ques['Answer_Label']

    # Train model
    model = LogisticRegression()
    model.fit(X, y)

    return model, vectorizer, le

# Load everything
model, vectorizer, label_encoder = load_model_and_data()

# UI Setup
st.set_page_config(page_title="Kamaraj College FAQ Chatbot", layout="centered")
st.title("🎓 Kamaraj College FAQ Chatbot")
st.write("Ask any question related to **Kamaraj College of Engineering and Technology**:")

# Input from user
user_question = st.text_input("💬 Enter your question:")

if st.button("🔍 Get Answer"):
    if user_question.strip() == "":
        st.warning("⚠️ Please enter a question.")
    else:
        # Vectorize and predict
        vector = vectorizer.transform([user_question])
        prediction = model.predict(vector)[0]
        answer = label_encoder.inverse_transform([prediction])[0]

        # Display result
        st.success(f"🟢 Answer: {answer}")